Dhali-org/Dhali-wallet

lib/dhali_wallet.dart, lib/main.dart, test/dhali_wallet_test.dart
* Allows image assets to be available when `dhali_wallet` is consumed from another project
* Enables wallet colors to be configured
* `flutter run`
=> Color configuration and asset access

lib/dhali_wallet.dart, lib/wallet_types.dart, lib/xrpl_wallet.dart, test/dhali_wallet_test.mocks.dart
* Creates abstract methods for `DhaliWallet` and overrides them from `XRPLWallet`
=> Create abstract methods for dhali_wallet

lib/dhali_wallet.dart, lib/xrpl_wallet.dart, test/dhali_wallet_test.mocks.dart
* Replaces sendDrops as abstract method with preparePayment
* `flutter run`
=> Replace sendDrops as abstract method with preparePayment

lib/xrpl_wallet.dart
Sets balance of XRP wallet to be the amount of XRP in the channel
=> Fix XRP wallet balance

lib/xrpl_wallet.dart, pubspec.yaml
* adds xrpl wallet support for `PaymentChannelFund` transactions
* Blocked on [this PR](https://github.com/Dhali-org/xrpl.dart/pull/11) - I will need to update the `pubspec.yaml` in this repo to consume a new tag from `xrpl.dart`, once that's been merged.  Will upgrade from a draft once this is done
=> add xrpl wallet 'fundPaymentChannel'

lib/dhali_wallet_widget.dart, lib/xumm_wallet_widget.dart
* Adds on activation button to XUMM wallet
* Check the button presents itself when logging into XUMM
=> Add Xumm onactivation button

lib/dhali_wallet_widget.dart
=> Default to XummWallet if prev activated

lib/dhali_wallet_widget.dart, lib/xrpl_wallet.dart, lib/xumm_wallet.dart, test/dhali_wallet_test.dart
* Ensures balances calculated correctly and consistently  across wallets
* Defaults to active wallets tab if an active wallet is available
* Activate raw XRP wallet
* Activate XUMM
* Fund XUMM and ensure it increments
=> Correct balance calculation

lib/xumm_wallet_widget.dart, test/dhali_wallet_test.dart
=> Loading -> Linked

lib/xrpl_wallet.dart, lib/xumm_wallet.dart, lib/xumm_wallet_widget.dart
* Removes textColor from XUMM balance. This allows the text color to consume the underlying theme color
* Performs client.disconnect appropriately for XRPL wallet
* Implements NFT related methods for XUMM
* Activate an XRP wallet
* Download your words
* Activate a XUMM wallet
* Reactivate you XRPL wallet
* Reactivate your XUMM wallet
=> Support XUMM in marketplace

lib/xrpl_wallet.dart
=> fix fund payment channel

lib/xrpl_wallet.dart
=> Fix PayChannel checking

lib/dhali_wallet_widget.dart
* Removes the AppBar so that the consuming application can take control over app navigation
=> Remove AppBar

lib/dhali_wallet_widget.dart
=> Use free test wallet

lib/dhali_wallet_widget.dart
=> Make tabs clearer

lib/dhali_wallet_widget.dart
=> Increase selected tab highlight

lib/dhali_wallet_widget.dart, lib/xrpl_wallet_widget.dart, pubspec.yaml
=> Make Xumm wallet persist

lib/dhali_wallet_widget.dart
=> Fix: tab not animating to when XUMM loaded

lib/dhali_wallet_widget.dart
=> Call onActivation if wallet loaded

lib/dhali_wallet_widget.dart, lib/main.dart, lib/widgets/buttons.dart, lib/xrpl_wallet.dart, lib/xrpl_wallet_widget.dart, lib/xumm_wallet.dart, test/dhali_wallet_test.dart, test/dhali_wallet_test.mocks.dart
=> Add consistent styling to buttons

lib/xrpl_wallet.dart, lib/xumm_wallet.dart
=> add mainnet support

lib/xumm_wallet.dart
* Open XUMM wallet and check the dialog can be closed
=> Auto pop XUMM dialog

lib/widgets/buttons.dart, lib/xrpl_wallet_widget.dart
=> Make fund dhali balance button pressable only when input available

lib/xrpl_wallet.dart, lib/xumm_wallet.dart
* This PR reduces the settle delay from 6 months to 2 weeks. This is because Dhali now only requires payment channels to be open for a minimum of 2 weeks
=> Settle delay 6 months -> 2 weeks

lib/xrpl_wallet.dart, lib/xrpl_wallet_widget.dart, lib/xumm_wallet.dart
* Without this, the users Dhali balance in the app will not update after deployment
* This bug was spotted during user feedback sessions
=> Update Dhali wallet

.github/workflows/firebase-hosting-xumm-iframe-merge-staging.yml
=> Update action name

lib/dhali_wallet_widget.dart, lib/xrpl_wallet_widget.dart, test/dhali_wallet_test.dart
=> Remove raw wallet

lib/dhali_wallet_widget.dart, lib/xrpl_wallet_widget.dart, test/dhali_wallet_test.dart
=> Revert raw

lib/main.xumm.dart, lib/xrpl_wallet_widget.dart
=> Add logout button

lib/xrpl_wallet_widget.dart, test/dhali_wallet_test.dart
=> Simplify address/logout button

lib/xrpl_wallet_widget.dart
=> Add usage instructions
